name: cliTests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  # include "slow" tests that make node requests, as well as mocks
  POLYGONETL_RUN_SLOW_TESTS: true
  POLYGONETL_PROVIDER_URI: ${{ secrets.POLYGONETL_PROVIDER_URI }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: polygon-etl cli tests
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd cli
          pip install -e .[dev,streaming]

      - name: Run pytest on cli
        run: |
          cd cli
          python -m pytest -vv
