name: validateJsonTest

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: polygon-etl validate json test
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.12"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install \
            --upgrade pip \
            -r requirements_test.txt
      - name: Run pytest on tests
        run: pytest -vv tests
